# Generated by Django 5.2.7 on 2025-10-05 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_datedcompleted_task_datecompleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Avanzado', 'Avanzado'), ('Observador', 'Observador')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_simulacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaludOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=100)),
                ('casos_asma', models.IntegerField()),
                ('casos_bronquitis', models.IntegerField()),
                ('hospitalizaciones', models.IntegerField()),
                ('mortalidad', models.IntegerField()),
                ('fecha_registro', models.DateTimeField()),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_resultado', models.CharField(choices=[('Diagrama causal', 'Diagrama causal'), ('Tornado chart', 'Tornado chart'), ('Gráfica de dispersión', 'Gráfica de dispersión'), ('Bandas de incertidumbre', 'Bandas de incertidumbre'), ('Gráfica de fases', 'Gráfica de fases')], max_length=50)),
                ('archivo', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPG')], max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='ExposicionOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=100)),
                ('tamaño_poblacion', models.IntegerField()),
                ('tiempo_exposicion', models.FloatField()),
                ('nivel_exposicion', models.FloatField()),
                ('fecha_registro', models.DateTimeField()),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='EmisionesOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fuente', models.CharField(max_length=100)),
                ('gas', models.CharField(max_length=50)),
                ('tasa_emision', models.FloatField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('fecha_registro', models.DateTimeField()),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='DispersionOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.CharField(max_length=50)),
                ('velocidad_viento', models.FloatField()),
                ('direccion_viento', models.CharField(max_length=20)),
                ('temperatura', models.FloatField()),
                ('concentracion', models.FloatField()),
                ('fecha_registro', models.DateTimeField()),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tabla', models.CharField(choices=[('Emisiones', 'Emisiones'), ('Dispersión', 'Dispersión'), ('Exposición', 'Exposición'), ('Salud', 'Salud'), ('Social', 'Social')], max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='SocialOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medida', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_implementacion', models.DateField()),
                ('impacto_estimado', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='VariablesDispersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracion_BTX', models.FloatField()),
                ('velocidad_viento', models.FloatField()),
                ('direccion_viento', models.CharField(max_length=20)),
                ('altura_mezcla', models.FloatField()),
                ('radiacion_solar', models.FloatField()),
                ('vida_media_BTX', models.FloatField()),
                ('simulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='VariablesEmisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parque_vehicular', models.IntegerField()),
                ('inventario_industrial', models.IntegerField()),
                ('factor_emision', models.FloatField()),
                ('kilometraje_promedio', models.FloatField()),
                ('consumo_combustible', models.FloatField()),
                ('eficiencia_control', models.FloatField()),
                ('politica', models.CharField(max_length=100)),
                ('simulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='VariablesExposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poblacion_zona', models.IntegerField()),
                ('tiempo_exposicion', models.FloatField()),
                ('infiltracion', models.FloatField()),
                ('microambiente', models.CharField(max_length=100)),
                ('uso_proteccion', models.BooleanField(default=False)),
                ('simulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='VariablesSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casos_respiratorios', models.IntegerField()),
                ('hospitalizaciones', models.IntegerField()),
                ('urgencias', models.IntegerField()),
                ('incidencia_base', models.FloatField()),
                ('coeficiente_beta', models.FloatField()),
                ('lag_dias', models.IntegerField()),
                ('simulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='VariablesSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_publica', models.FloatField()),
                ('inversion_tp', models.FloatField()),
                ('capacidad_vigilancia', models.FloatField()),
                ('adopcion_tecnologica', models.FloatField()),
                ('cumplimiento_normativo', models.FloatField()),
                ('simulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.simulacion')),
            ],
        ),
    ]
