# Generated by Django 5.2.7 on 2025-10-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_perfilusuario_simulacion_saludoriginal_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archivos_procesados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
