# Generated by Django 5.2.7 on 2025-10-08 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_archivos_procesados_task_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivoexcel',
            name='nombre_archivo',
        ),
        migrations.RemoveField(
            model_name='archivoexcel',
            name='ruta_archivo',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='archivo',
        ),
        migrations.AddField(
            model_name='archivoexcel',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_excel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv'])]),
        ),
        migrations.AddField(
            model_name='resultado',
            name='imagen',
            field=models.ImageField(default=None, upload_to='resultados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulacion',
            name='datos_txt',
            field=models.FileField(blank=True, null=True, upload_to='simulaciones_txt/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='formato',
            field=models.CharField(default='JPG', max_length=10),
        ),
    ]
