# Generated by Django 5.2.7 on 2025-10-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_archivoexcel_nombre_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='nombre',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
