# Generated by Django 5.2.7 on 2025-10-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_descripcion_task_estado_task_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='task',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='task',
            name='nombre',
        ),
    ]
