# Generated by Django 5.2.7 on 2025-10-12 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_descripcion_remove_task_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoexcel',
            name='archivo',
            field=models.FileField(upload_to='archivos_excel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv'])]),
        ),
    ]
