# Generated by Django 5.2.7 on 2025-10-12 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_archivoexcel_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoexcel',
            name='archivo',
            field=models.FileField(upload_to='archivos_excel/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv'])]),
        ),
    ]
