# Generated by Django 5.2.7 on 2025-10-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_archivoexcel_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('completada', 'Completada')], default='borrador', max_length=20),
        ),
    ]
