# Generated by Django 4.2.25 on 2025-10-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_simulacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoexcel',
            name='errores_validacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivoexcel',
            name='num_filas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivoexcel',
            name='valido',
            field=models.BooleanField(default=False),
        ),
    ]
